### ISSUE TITLE
Caddyfile support

### ISSUE THREAD

**Issue by yroc92** [yroc92/postgres-storage#5]
Add support for the Caddyfile config format. Right now it can only be configured with the native JSON format.

**Comment by gabrielmocan** [comment]
What are the guidelines to do that? I need to use this plugin with https://github.com/lucaslorentz/caddy-docker-proxy but I'm having trouble to configure the storage spec.

**Comment by yroc92** [comment]
I haven't needed the Caddyfile configuration for this plugin myself, but all that needs to be done is to implement `UnmarshalCaddyfile`. Here are [the docs](https://caddyserver.com/docs/extending-caddy/caddyfile#unmarshaler) that describe it.

As an example, see [how this Amazon S3 Storage module implements it](https://github.com/ss098/certmagic-s3/blob/master/s3.go#L38).

**Comment by gabrielmocan** [comment]
I've forked the project and working on it. Once I'm done, will submit PR.

**Comment by gabrielmocan** [comment]
A couple PRs submitted @yroc92 so you can appreciate.

**Comment by yroc92** [comment]
@gabrielmocan thank you for the PR's! I should be able to take a look at these by the end of this week.

**Comment by yroc92** [comment]
Resolved by https://github.com/yroc92/postgres-storage/pull/9

**Comment by gabrielmocan** [comment]
Glad to help here.

**Comment by yroc92** [comment]
@gabrielmocan https://twitter.com/yroc92/status/1610056831682113537?s=46&t=h8jjWuBRSek8iN35kua1YA
